name: flex-alloc
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full
  RUST_LOG: debug
  RUST_LOG_STYLE: always
  RUST_VERSION: stable 6 months ago

defaults:
  run:
    shell: bash

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUST_VERSION }}
          components: clippy, rustfmt

      - name: Cargo check
        run: cargo check

      - name: Cargo check (no default features)
        run: cargo check --no-default-features

      - name: Cargo test
        run: cargo test --features zeroize

      - name: Cargo test (no default features)
        run: cargo test --no-default-features

      - name: Cargo format
        run: cargo fmt --all -- --check

      - name: Cargo clippy
        # run: cargo clippy --features zeroize -- -Dwarnings
        run: cargo clippy --features zeroize
